baseurl: "https://dsconf.in/"
title: "Distributed Systems Conference"
canonifyurls: true
theme: "ds-conf"

GoogleAnalytics: "UA-115518698-1"

params:
  # Conference info
  Name: "Distributed Systems Conference"
  Description: "Best Practices | Future of Distributed Systems"
  Date: "April 21"
  Price: "" # If your event is free, just comment this line
  Venue: "Hotel Shereton Grand"
  Address: "Hotel Shereton Grand, Raja Bahadur Mill Rd"
  City:  "Pune"
  State: "Maharashtra"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "AIzaSyBn2ym7eC7ljBuWwxZgJ-U9gbKCIMk43rQ"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections: 
    - speakers
    - schedule
    - about
    - location
    - sponsors
    
    # - sponsors
    # - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://www.townscript.com/e/distributed-systems-conference-003402"

  # # List of Sponsors
  # Sponsors:
  #   - name: "Hugo"
  #     logo: "/img/hugo.png"
  #     url: "http://gohugo.io"

  # # List of Partners
  # Partners:
  #   - name: "Hugo"
  #     logo: "/img/hugo.jpg"
  #     url: "https://gohugo.io"
  #   - name: "BrazilJS"
  #     logo: "/img/partner.png"
  #     url: "http://braziljs.org"

  # The entire schedule
  Speakers: 
    - name: "Dr. Sriram Srinivasan"
      photo: "img/sriram.jpg"
      bio: " Dr. Sriram Srinivasan is a systems and programming languages geek with 30+ years of experience, from embedded devices to large-scale distributed systems and frameworks. He was one of the  principal designers and implementors of the Weblogic application server. He has a PhD from the Univ. of Cambridge and teaches Distributed Systems at IIT Bombay."
      talk: 
        title: "The Many Flavours Of Consensus"
        href: "/#id1"
      link:
        href: "https://github.com/sriram-srinivasan"
        text: "@Sriram"

    - name: "Dr. Sandeep Deshmukh"
      photo: "img/sandeep-deshmukh.jpg"
      bio: "Dr Sandeep Deshmukh completed his PhD from IIT Bombay and has been working in Big Data and Hadoop ecosystem for 7+ years. He has executed complex projects in different domains in a distributed computing environment. He loves teaching and interacting with people and has conducted numerous workshops on Hadoop and Apache Apex. Currently Sandeep is a Trainer and Consultant for Big Data, Hadoop and Apache Apex."
      talk: 
        title: "Operability and Observability of Big Data Ecosystems"
        href: "/#id2"
      link:
        href: "https://github.com/sandeepdeshmukh"
        text: "@Sandeep"
    
    - name: "Sriram Ramachandrasekaran"
      photo: "img/sriram-indix.jpg"
      bio: "Sriram is a Principal Engineer @ Indix. Apart from writing code to foot his bills, he does it to get some adrenaline going, when he is not riding his bike on unchartered terrains. He is co-author of Suuchi project along with his fellow engineer Ashwanth kumar. Currently, he works on problems involving ML at Indix."      
      talk: 
        title: "Why we built a distributed system"
        href: "/#id3"
      link:
        href: "https://github.com/brewkode"
        text: "@Sriram"
    - name: "Ashwanth Kumar"
      photo: "img/aswant.jpeg"
      bio: "Ashwanth Kumar is a Principal Software Engineer @indix. While he's not fiddling with distributed Systems and data, he contributes to Open Source and helps organise meetups and tech events in the City. He writes Scala at work and Go at home."
      talk: 
        title: "Why we built a distributed system"
        href: "/#id3"
      link:
        href: "https://github.com/ashwanthkumar"
        text: "@Sriram"
        
  Schedule:
    - presentation:
        title: "Registration"
        description: ""
        time: "9.00"
        id: "id1"

    - presentation:
        title: "The Many Flavours Of Consensus"
        description: " Consensus is the act of agreement amongst distributed participants. This talk will try to make sense of the wide variety of problems and solutions that are lumped under the consensus label:  two-phase commit, byzantine agreement, paxos/raft, bitcoin and so on."
        time: "TBD"
        id: "id2"

    - presentation:
        title: "Operability and Observability of Big Data Ecosystem"
        description: "Most of the big data systems project don’t make it to production. We would dive into the reasons for the same and how  the situation can be improved by taking into consideration oberverability and operablity. We will present why and how operability is important, and how it directly results in lower TCO and quicker TTV. These are critical needs for big data projects to succeed, and for big data to be mass market. Big data needs to be productized and operationalized."
        time: "TBD"
        id: "id3"
        
  
    - presentation:
        title: "Why we built a distributed system"
        description: "At Indix, we have a bunch of services that need to operate on top of large volume of product data. We started out with using open source distributed systems (like Hadoop, HBase, Solr, Spark, etc) to build some of our solutions. Along the way, we’ve also had problems where existing solutions wouldn’t really work for our requirements and operational cost associated with them started to shoot up. This pushed us to build a couple of “simple” distributed systems.
                    With this context, we started out building Suuchi⁰, a toolkit for building distributed data systems."
        time: "TBD"
        id: "id4"

    - presentation:
        title: "To be added later"
        description: ""
        time: "TBD"
        id: "id5"

  Sponsors:
    - name: "ThoughtWorks"
      logo: "img/thoughtworks-logo.png"
      url: "https://www.thoughtworks.com"
      type: "platinum"
    - name: "ThoughtWorks"
      logo: "img/thoughtworks-logo.png"
      url: "https://www.thoughtworks.com"
      type: "gold"
    - name: "ThoughtWorks"
      logo: "img/thoughtworks-logo.png"
      url: "https://www.thoughtworks.com"
      type: "Community"
    - name: "ThoughtWorks"
      logo: "img/thoughtworks-logo.png"
      url: "https://www.thoughtworks.com"
      type: "community"